import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {process.env.NEXT_PUBLIC_COOKIE_SCRIPT_TEST && (
          <Script
            id="cookie-banner"
            src={process.env. NEXT_PUBLIC_COOKIE_SCRIPT_TEST}
          />
        )}
        <div className="flex min-h-screen">
          <nav className="w-64 p-4 border-r flex flex-col gap-2 shrink-0">
            <Link href="/" className="text-blue-600 hover:underline">
              Home (Link)
            </Link>

            <div className="mt-4 mb-1 text-xs font-semibold text-gray-500 uppercase">
              Link (default prefetch)
            </div>
            <Link href="/client-component" className="text-blue-600 hover:underline">
              Client Component
            </Link>
            <Link href="/server-component" className="text-blue-600 hover:underline">
              Server Component
            </Link>

            <div className="mt-4 mb-1 text-xs font-semibold text-gray-500 uppercase">
              Link (prefetch=true)
            </div>
            <Link href="/client-component" prefetch={true} className="text-blue-600 hover:underline">
              Client Component
            </Link>
            <Link href="/server-component" prefetch={true} className="text-blue-600 hover:underline">
              Server Component 
            </Link>

            <div className="mt-4 mb-1 text-xs font-semibold text-gray-500 uppercase">
              Link (prefetch=false)
            </div>
            <Link href="/client-component" prefetch={false} className="text-blue-600 hover:underline">
              Client Component
            </Link>
            <Link href="/server-component" prefetch={false} className="text-blue-600 hover:underline">
              Server Component
            </Link>

            <div className="mt-4 mb-1 text-xs font-semibold text-gray-500 uppercase">
              Plain &lt;a&gt; tag
            </div>
            <a href="/client-component" className="text-blue-600 hover:underline">
              Client Component
            </a>
            <a href="/server-component" className="text-blue-600 hover:underline">
              Server Component
            </a>

            <div className="mt-4 pt-4 border-t">
              <a
                href="https://github.com/GabeStah/osano-next-16"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-500 hover:text-gray-700 text-sm flex items-center gap-2"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
                GitHub Repo
              </a>
            </div>
          </nav>
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
